### ISSUE TITLE
We need a proper name for the language

### ISSUE THREAD

**Issue by RupertAvery** [Maximilian-Winter/Bite-Programming-Language#1]
I hereby propose the name Srsly, pronounced "Seriously" in the pattern of suffixing -ly to, uh, things.

This is a half-meant joke, like all good programming languages are so named.

Much better than Srsl or SrslBytecodeVmAndCodeGenerator.

So:

Srsly, a C# based embedded language/Bytecode VM and Code Generator

**Comment by Maximilian-Winter** [comment]
Hey, Thank you. I just talked with a couple of friends about the language name. And they suggested "Bite" as a name. What do you think of it?

**Comment by Maximilian-Winter** [comment]
But I have to say Srsly is also great!

**Comment by RupertAvery** [comment]
I'm partial to Srsly ("Sers-ly" perhaps is an alternative pronunciation to "Seriously") of course, but as the creator of the language it's up to you! :)

There is already a cs-script of course.

**Comment by Maximilian-Winter** [comment]
I renamed it to Bite
