### ISSUE TITLE
Parser bug?

### ISSUE THREAD

**Issue by RupertAvery** [Maximilian-Winter/Bite-Programming-Language#10]
I'm writing unit tests, because I know how painful it can be maintaining a parser/compiler from my experience building a C# (runtime) Expression Evaluator a while back.

I came across this bug when testing chained binary expressions. I've checked this with the pre-merge code and it exists there:

```
module MainModule;

import System;
using System;

import CSharpSystem;
using CSharpSystem;

var a = 2 * 5 - 4 / 2 + 6;

Console.WriteLine(a);  // actual = 2, expected = 14
```

This seems to work though:

```
1 * 2 + 3 * 4 // equals 14
```

It seems that the expression is being evaluated as:

```
(2 * 5) - ( (4 / 2) + 6 ) 
```

Which of course gives 2. This could be caused by right-side precedence in the parser?

To enable unit tests, I've added some code to be able to parse statements as well as expressions. It wraps an ExpressionNode in a StatementNode puts it in a ModuleNode in order for everything to work.

Here's an example of a unit test.

```

    private ExecResult ExecExpression(string expression)
    {
        var parser = new SrslParser();

        var expressionNode = parser.ParseExpression(expression);

        var generator = new CodeGenerator();

        var context = generator.CompileExpression(expressionNode);

        var srslVm = new SrslVm();

        var result = srslVm.Interpret(context);

        return new ExecResult()
        {
            InterpretResult = result,
            LastValue = srslVm.RetVal
        };
    }

    [Fact]
    public void AddNumbers()
    {
        var result = ExecExpression("1 + 1");
        Assert.Equal(SrslVmInterpretResult.InterpretOk, result.InterpretResult);
        Assert.Equal(2, result.LastValue.NumberData);
    }

```

The branch is here:

https://github.com/RupertAvery/SrslBytecodeVmAndCodeGenerator/tree/compilation_context

**Comment by Maximilian-Winter** [comment]
Thank you. I will look into this. I had an Ast Tree Walker that handled this cases better and had all language features implemented. But I switched to Bytecode VM one and a half months ago. The thing is, that it isnt really finished right now. I'm working on completeing the vm and then I will look into this.

**Comment by Maximilian-Winter** [comment]
I tested a little bit and the problem is the following code, the while loop is wrong, but I'm not quite sure how to fix it. Any Ideas?
`BinaryOperationNode firstOperationNode = new BinaryOperationNode();

                var context = multiplicative();

                if (context.Failed) return context;

                firstOperationNode.LeftOperand = context.Result;

                BinaryOperationNode currentOperationNode = firstOperationNode;

                while (LA(1) == SrslLexer.MinusOperator || LA(1) == SrslLexer.PlusOperator)
                {
                    if (LA(1) == SrslLexer.PlusOperator)
                    {
                        currentOperationNode.Operator = BinaryOperationNode.BinaryOperatorType.Plus;
                    }
                    else
                    {
                        currentOperationNode.Operator = BinaryOperationNode.BinaryOperatorType.Minus;
                    }

                    consume();

                    context = multiplicative();

                    if (context.Failed) return context;

                    ExpressionNode expressionNode = context.Result;

                    if (LA(1) == SrslLexer.MinusOperator || LA(1) == SrslLexer.PlusOperator)
                    {
                        BinaryOperationNode binaryOperationNode = new BinaryOperationNode();
                        currentOperationNode.RightOperand = binaryOperationNode;
                        currentOperationNode = binaryOperationNode;
                        currentOperationNode.LeftOperand = expressionNode;
                    }
                    else
                    {
                        currentOperationNode.RightOperand = expressionNode;
                    }
                }

                if (firstOperationNode.RightOperand != null)
                {
                    return new Context<ExpressionNode>(firstOperationNode);
                }

                return new Context<ExpressionNode>(firstOperationNode.LeftOperand);
            }`

**Comment by Maximilian-Winter** [comment]
The chaining of the binary operation is wrong.

**Comment by Maximilian-Winter** [comment]
Ok I fixed the chaining of the nodes and now it giving me the right result.
