### ISSUE TITLE
Allow else if

### ISSUE THREAD

**Issue by RupertAvery** [Maximilian-Winter/Bite-Programming-Language#18]
## Test

```
var a = "fee"; 
var b = "bar"; 
var c = 789; 
if (a == "foo") 
{ 
   c = 123; 
} else if (b == "bar") 
{  
   c = 456; 
}
```

**Expected**

b = 456;

**Actual** 

Object reference not set to an instance of an object.
   at Bite.Runtime.CodeGen.CodeGenerator.Visit(CallNode node) in D:\...\Bite\Runtime\CodeGenerator\CodeGenerator.cs:line 602

## Affected Tests

- IfElseIfTrue
- IfElseIfFalseThenTrue
- IfElseIfFalseThenFalse
- IfElseIfElse

**Comment by RupertAvery** [comment]
For some reason the `AstNodeScope` for the symbol `b` in the second `if` statement is null.

**Comment by Maximilian-Winter** [comment]
The problem was in the symbol table builder. I also added string comparison.
