### ISSUE TITLE
Assignment of an arithmetic assignment

### ISSUE THREAD

**Issue by RupertAvery** [Maximilian-Winter/Bite-Programming-Language#22]
Any assignment expression should push the value on the stack.

# Test

```
var a = 1;
var b = a += 2;
```

**Expected**

b = 3

**Actual**

```
System.IndexOutOfRangeException : Index was outside the bounds of the array.

DynamicBiteVariableStack.Pop() line 68
BiteVm.Run() line 531
BiteVm.Interpret(BiteProgram context) line 89
BiteProgram.Run() line 56
StatementUnitTests.ExecStatements(String statements) line 21
StatementUnitTests.ArithmeticAssignmentAssignment() line 75
```

It looks like this can be fixed just by pushing the value back on the stack, however there are a lot of cases I'm not sure how to test yet.

Any expression including assignment of member variables, element assignment, not sure how to test  `m_SetMemberWithString`. Is this like dynamic member access with `obj["property"]` ?

Also need to test as a function argument, 

e.g.

```
foo(a += 2)   // argument should recieve "3"
```

**Comment by RupertAvery** [comment]
Also need to watch out for operator precedence

```
var b = (a += 2) + 3;  // increments a by 2, adds the result to 3, assigns to b
```

Is different from

```
var b = a += 2 + 3;  // increments a by 5, assigns to b
```

though this should be naturally handled by the grammar precedence rules

**Comment by Maximilian-Winter** [comment]
Should be fixed with the latest commit
