### ISSUE TITLE
Catch errors related to symbols / compilation issues and throw a more context-useful error

### ISSUE THREAD

**Issue by RupertAvery** [Maximilian-Winter/Bite-Programming-Language#30]
We should create more specific exception classes and return errors that resemble compiler issues, instead of .NET errors.

## Example

Access an undefined variable x;

## Expected

The name 'x' does not exist in the current context - C# sample message

## Actual

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

**Comment by Maximilian-Winter** [comment]
Fixed with the latest commit.
