### ISSUE TITLE
Shorter syntax for C# object calls

### ISSUE THREAD

**Issue by IAmJonas1234** [Maximilian-Winter/Bite-Programming-Language#45]
Instead of
````
var interface = new CSharpInterface();
interface.Type = "System.Console";
var Console = CSharpInterfaceCall(CSharpInterfaceObject);
````
you should be able to just write
````
var Console = CSharpInterfaceCall("System.Console");
````

**Comment by Maximilian-Winter** [comment]
This is a good Idea!

**Comment by Maximilian-Winter** [comment]
I'm currently working on a closer csharp integration. I will keep that in mind.

**Comment by Maximilian-Winter** [comment]
Ok I just implemented this in the C# Interface. Will be in the next release. Or in the code right now.

**Comment by Maximilian-Winter** [comment]
Branch is merged into master!

**Comment by vorov2** [comment]
And why do you call this CSharp interface? Basically this can be any .NET language

**Comment by Maximilian-Winter** [comment]
Yes, you are right about that. But I use it mainly as a C# interface. And I never tried it with other .NET languages

**Comment by Maximilian-Winter** [comment]
And I think currently only C# should work. Not sure about other net languages.

**Comment by Maximilian-Winter** [comment]
I should change this. In future it will be Net Language Interface

**Comment by Maximilian-Winter** [comment]
Never realised that I could also use other net languages.

**Comment by Maximilian-Winter** [comment]
Is released.
