### ISSUE TITLE
No recursion?

### ISSUE THREAD

**Issue by vorov2** [Maximilian-Winter/Bite-Programming-Language#47]
```
> function fib(n) { if (n < 2) return n; else return fib(n-1) + fib(n-2); }
Compiler Error: Name 'fib' not found in current program!
```

**Comment by Maximilian-Winter** [comment]
This should work. Will fix this asap! Sorry for the bug. And thank you for brining it to my attention.

**Comment by Maximilian-Winter** [comment]
Is fixed in the new release.
https://github.com/Maximilian-Winter/Bite-Programming-Language/releases/tag/alpha-release-v0.1.4
