### ISSUE TITLE
NetLanguageInterface

### ISSUE THREAD

**Issue by RupertAvery** [Maximilian-Winter/Bite-Programming-Language#48]
I'd like to suggest altering the NetLanguageInterface API.

My problems with it is

1) name is too long, but doesn't really describe what it does
2) NetLanguageInterface is a noun (or sounds more like a noun), but should be a verb as it does/returns something.
2) Ambiguous. Many functions are rolled up into it.  Get a constant? Execute a constructor?  A method?
3) interleaving of types and values as arguments. Everytime the same method is called, you need to repeat the information.

I propose a module named `System.Interop`  or perhaps more descriptive `System.Reflection` with the following functions:

`GetConstructor(type, parameter_type, parameter_type, ...)`

Returns a function, that when called, returns a new instance of the type, using the specified type parameters

`GetMember(type, member_name)`

Returns the value of the constant on the static type

`GetMethod(type, parameter_type, parameter_type, ..)`  

Returns a method that calls the type's method on an instance.

## Old Syntax

```cs
var img = NetLanguageInterface("Bitmap", true, xres, "int", yres, "int");
var imgFormat = NetLanguageInterface("ImageFormat", "Png");
var colorBlack = NetLanguageInterface("Color", "Black");
var colorBrown = NetLanguageInterface("Color", "Brown");
```

## Proposed syntax

```cs
var bitmapConstructor = Interop.GetConstructor("Bitmap", "int", "int");

var img = bitmapConstructor(xres, yres);

var imgFormat = Interop.GetMember("ImageFormat", "Png");
var colorBlack = Interop.GetMember("Color", "Black");
var colorBrown = Interop.GetMember("Color", "Brown");
var setPixel = Interop.GetMethod("SetPixel", "int", "int", "Color");

...

setPixel(img, x, y, colorBlack);


```

We might need new interfaces for `GetConstructor` and `GetMethod`.

**Comment by vorov2** [comment]
`Interop` seems like a pretty natural choice. And the whole concept is similar to what I use:
https://github.com/vorov2/dyalect/wiki/Interop

**Comment by RupertAvery** [comment]
What I've done is basically separate the  `ForeignLibraryInterfaceVm` into multiple classes, `InteropGetConstructor` and `InteropGetMethod` which return a `ConstructorInvoker` and `MethodInvoker` respectively, which themselves are also IBiteVmCallables.

The `MethodInvoker` acts like a method cache that is tied to the lifetime / scope of the variable it is assigned to.

I made a benchmark which calls these methods directly (i.e. not through a bite program)

```
|                       Method |        Mean |     Error |    StdDev |      Median |
|----------------------------- |------------:|----------:|----------:|------------:|


| RunForeignLibraryInterfaceVm | 525.8688 ns | 5.8243 ns | 4.8636 ns | 525.6908 ns |
|                RunReflection | 295.7636 ns | 4.9093 ns | 4.0995 ns | 294.5568 ns |
|          RunInteropGetMethod | 156.3701 ns | 1.3676 ns | 1.2792 ns | 156.3909 ns |
|                    RunNative |   0.0057 ns | 0.0107 ns | 0.0095 ns |   0.0000 ns
```

The tests run the invocation code only, except for `RunForeignLibraryInterfaceVm` which has some reflection built into it.

The idea of the Interop* methods is that reflection / type resolution is only done once, and type info is only needed during reflection.

The `InteropGetMethod` uses `FastMethodInfo` which is around 100ns faster than a simple memberinfo `Invoke`.

These are pretty good improvements, but on normal scale of millions of calls a difference of 400ns per call isn't really noticeable.  4 million nanoseconds is "just" 0.4 seconds, or 400 milliseconds.

So benchmarks around calls should be made with very isolated tests in order to see the difference.

**Comment by vorov2** [comment]
Personally I think that caching is a kind of optimization that can be applied after the whole interface is stabilized. It can be always implemented afterwards as an optimization layer. I mean - usability (in the way how API works) first, optimization second - this is what I would normally expect from a dynamic language environment. 

Types can be easily cached but that's not true for overloaded methods where you have to perform overload resolution at run-time and different overloads might have very minor differences. If you *have* to use `GetMethod` to invoke method every time - with no support for direct method call - that is exactly the case where I would sacrifice performance for usability.

**Comment by RupertAvery** [comment]
True, the caching mechanism here just naturally arises out of assigning the result of reflection.  By declaring the arguments of the method you want to call you are effectively locking them in. Therefore if you perchance pass arguments that are not of the expected type, then it should fail as a runtime error.

This isn't the same when you call a method on a dynamic object, where you specify the name of the method you want to call at the callsite, and the arguments are dynamic.  In this case as you mentioned, you _have_ to resort to reflection, as the parameter types aren't guaranteed to be fixed.

**Comment by Maximilian-Winter** [comment]
Yes, you two are right. Will change the net language interface to Interop and do it the way proposed
