### ISSUE TITLE
import / using feels redundant

### ISSUE THREAD

**Issue by RupertAvery** [Maximilian-Winter/Bite-Programming-Language#6]
Can this be rolled into one statement?  Just `import` perhaps?

```
import System;
using System;

import CSharpSystem;
using CSharpSystem;
```

**Comment by Maximilian-Winter** [comment]
I implemented this to provide an easy way to access other modules. One can choose to use the full qualified name without the using and just use the import. Or you can say you "using 'modulename'" and you can write the module inter name. I did this also for name conflicts.
